import Navbar from './components/Navbar';
import './globals.css'
import { Nunito } from 'next/font/google'
import { StoreProvider } from './utils/store';

const font = Nunito({ 
  subsets: ['latin'], 
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <StoreProvider>
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
